### ISSUE TITLE
Re-add Camera support

### ISSUE THREAD

**Issue by 32-bit-link** [jamesbt365/jamespy#8]
Camera support is a really important and useful feature of jamespy and it's why I (and many others) use jamespy.

I hope you reconsider your decision to phase out camera support in jamespy.

**Comment by jamesbt365** [comment]
The camera support feature brought potential security issues with leaking personal information that I am not interested in mitigating. I may reconsider this in the future, but for the foreseeable feature I will not be supporting this feature.
